# -*- coding: utf-8 -*-

import time                             #RE ENABLE THE GPIO!!!!--------------------------------------------------
import pygame
import os

import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(18,GPIO.OUT)

pygame.mixer.pre_init(44100, -16, 2 , 2048)
pygame.init()
pygame.mixer.init()
pygame.mixer.music.load("NASA_countdown_20sec.wav")

t = (.75)

clear = lambda: os.system('clear')

time.sleep(0)
clear()

print ('-----------------------------------------------')
print ('------------ Welcome To NASA OS ---------------')
print ('-----------------------------------------------')
print ('')
print ('256k Ram Check...')
time.sleep(1)
print('OK!')
print('')
time.sleep(1)
print ('please wait, Starting systems')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(1)
print ('Systems Started!')
GPIO.output(18,GPIO.HIGH)
time.sleep(.5)
GPIO.output(18,GPIO.LOW)
print ('')

time.sleep(1)
print("Start Preflight Checks? (1) Yes or (2) No\n")
time.sleep(.5)
print ('Auto input: = 1')
time.sleep(.5)

clear()
print ('')
print ('Starting Preflight Checks...')
print ('')
time.sleep(t)
print ('T-27 hours and counting...')
time.sleep(t)
print ('    Loading cryogenic reactants into the orbiter fuel cell storage tanks')
print ('')
time.sleep(t)
print ('T-19 hours and holding...')
time.sleep(t)
print ('    External nosecone tank purge')
print ('')
GPIO.output(18,GPIO.HIGH)   #PLC PULSE 2 ON      -----------------------------------------------RPI----------------------------------------------------------------
time.sleep(t)
GPIO.output(18,GPIO.LOW)    #PLC PULSE 2 OFF     -----------------------------------------------RPI----------------------------------------------------------------
print ('T-19 hours and counting')
time.sleep(t)
print ('    Filling launch pad sound suppression system water tank')
print ('')
time.sleep(t)
print ('T-11 hours and counting...')
time.sleep(t)
print ('    Activate the orbiter fuel cells')
time.sleep(t)
print ('    Switch the orbiters purge air to gaseous nitrogen')
print ('')
time.sleep(t)
print ('T-3 hours and counting...')
time.sleep(t)
print ('    Checking cockpit switch configurations')
time.sleep(t)
print ('    Initializing air-to-ground communication check')
time.sleep(t)
print ('    Checking for hatch leaks')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('    Systems Passed')
clear()
time.sleep(t)
print ('T-20 MINUTES and counting')
time.sleep(t)
print ('    Completing inertial measurement unit preflight alignments')
time.sleep(t)
print ('    Orbiter onboard computers changed to launch configuration')
print ('')
time.sleep(t)
print ('T-9 MINUTES and counting')
time.sleep(t)
print ('    Starting automatic ground launch sequencer')
time.sleep(t)
print ('    Retracting orbiter access arm')
time.sleep(t)
print ('    Starting auxiliary power units')
time.sleep(t)
print ('    Starting orbiter aerosurface profile test')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(t)
print ('    Systems Passed')
clear()
print ('    Retracting gaseous oxygen vent arm')      
time.sleep(t)
print ('    Transfering orbiter power from ground to internal')
time.sleep(t)
print ('    Activating launch pad sound suppression system')
print ('')
time.sleep(t)
print ('    Activating main engine hydrogen burn off system')
print ('')
time.sleep(t)
print ('    Activated main engine hydrogen burn off system')
clear()
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
clear()
print ('Loading Coordinates...')
time.sleep(1)
clear()
print ('Landing Coordinates:')
time.sleep(t)
print('N_5.0667° W_77.333° ±20^2 mi')
time.sleep(1) 
print('')
print ("Number Match?\n (1) Yes or (2) No\n")
time.sleep(.5)
print('Auto Input = 1')

GPIO.output(18,GPIO.HIGH) #plc pulse on 3
print ('')
time.sleep(1)
print ('Loading Coordinates')
GPIO.output(18,GPIO.LOW)  #plc pulse off 3
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('.')
time.sleep(.5)
print ('Coordinates Loaded!')
time.sleep(.5)
clear()
GPIO.output(18,GPIO.HIGH) #PLC 4 on
pygame.mixer.music.play()
print ('')
print ('----Main engine starting----')
time.sleep(1)
GPIO.output(18,GPIO.LOW)  #plc 4 off
print ('---------Keep Clear!--------')
time.sleep(8.5)
print ('           10')
GPIO.output(18,GPIO.HIGH) #PLC 5 PULSE ON -----------------------------------------------RPI----------------------------------------------------------------
time.sleep(1)
print ('            9')
print('Ignition Sequence Start!')
GPIO.output(18,GPIO.LOW) #PLC 5 PULSE OFF -----------------------------------------------RPI----------------------------------------------------------------
time.sleep(1)
print ('            8')
time.sleep(1)
print ('            7')
time.sleep(1)
print ('            6')
time.sleep(1)
print ('            5')
time.sleep(1)
print ('            4')
time.sleep(1)
print ('            3')
GPIO.output(18,GPIO.HIGH) #PLC PULSE 6 ON (LAUNCH) -----------------------------------------------RPI----------------------------------------------------------------
time.sleep(1)
print ('            2')
GPIO.output(18,GPIO.LOW) #PLC PULSE 6 OFF          -----------------------------------------------RPI----------------------------------------------------------------
time.sleep(1)
print ('            1')
    
#Activate rocket engine
time.sleep(2)
print ('This is Mission Control, WE HAVE LIFT OFF!')
#leave time for audio
        
time.sleep(.75)
print ('       !')
print ('       !')
print ('       ^')
print ('      / \ ')
print ('     /___\ ')
print ('    |=   =|')
print ('    |     |')
print ('    |     |')   
print ('    |     |')
print ('    |     |')
print ('    |     |')
print ('    |     |')
print ('   /|##!##|\ ')
print (' /  |##!##|  \ ')
print ('|  / ^ | ^ \  |')
print ('| /  ( | )  \ |')
print ('|/   ( | )   \|')
print ('    ((   )) ')
print ('   ((  :  )) ')
print ('   ((  :  )) ')
print ('    ((   )) ')
print ('     (( )) ')    
print ('      ( ) ')
print ('       . ')
print ('       . ')
print ('       . ')
time.sleep(25)
exit()
# sources: https://www.nasa.gov/mission_pages/shuttle/launch/countdown101.html